name: glowrpt
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  add_2_calendar: ^3.0.1
  cached_network_image:
  cloud_firestore: ^4.9.2
  cupertino_icons: ^1.0.6
  data_table_2: ^2.5.8
  date_field: ^3.0.5
  draggable_bottom_sheet: ^1.0.2
  dropdown_search: ^5.0.6
  easy_search_bar: ^2.5.0
  expandable_page_view: ^1.0.17
  firebase_core: ^2.16.0
  firebase_messaging: ^14.6.8
  fl_chart: ^0.63.0
  flutter_html: ^3.0.0-beta.2
  flutter_polyline_points: ^2.0.0
  flutter_widget_from_html: ^0.9.1
  geocoding: ^2.1.0
  geolocator: any
  get: ^4.6.6
  google_fonts: ^4.0.4
  google_maps_flutter: ^2.5.0
  horizontal_data_table: ^4.3.1
  http: ^0.13.0
  image_picker: any
  intl: any
  json_annotation: ^4.8.1
  path_provider: any
  percent_indicator: ^4.2.3
  permission_handler: any
  printing: ^5.11.0
  screenshot: ^2.1.0
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.2.1
  shimmer: ^3.0.0
  smooth_star_rating_null_safety: ^1.0.4+2
  speedometer: ^1.1.2
  sqflite: ^2.3.0
  table_calendar: ^3.0.9
  url_launcher: ^6.1.14
  wechat_camera_picker: ^4.0.2
  




  toast: ^0.3.0
  pin_code_text_field: ^1.8.0
  loading_animation_widget:
#  liquid_progress_indicator: ^0.4.0
  provider: ^6.0.1
  photo_view: any
  flutter_barcode_scanner: ^2.0.0
  barcode_widget: ^2.0.1
  open_file_safe: ^3.2.3
  loadmore: ^2.0.1
  group_radio_button: ^1.1.0
  date_time_picker: ^2.0.0
  datetime_picker_formfield: ^2.0.0
  flutter_switch: ^0.3.2
  page_view_indicators: ^2.0.0
  flutter_colorpicker: ^1.0.3
  flutter_share: ^2.0.0
  carousel_slider: any
  webviewx: ^0.2.1
  place_picker: any
  map_launcher: ^3.1.0
  background_location_tracker: ^1.4.0
  number_to_words_english: ^2.0.2
  bluetooth_print: ^4.3.0
  
  


  flutter_pagewise: ^2.0.4
  liquid_progress_indicator_v2: ^0.5.0
  photo_manager: any
  flutter_carousel_widget: ^2.2.0
  # lecle_flutter_carousel_pro: ^0.0.3
  # lecle_flutter_carousel_pro: ^0.0.3




dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.1


dependency_overrides:
  http: ^1.1.0
  geolocator: ^10.1.0
  intl: ^0.17.0
  path_provider: ^2.0.0

flutter_launcher_name:
  name: "Glowsis Dashboard"




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/slider/
    - assets/icons/

