import 'package:get/get.dart';

class LocalString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'Company Name': 'Company Name',
          'User Name': 'User Name',
          'Password': 'Password',
          'Login': 'Login',
          'Consolidated Attendance from all branches':
              'Consolidated Attendance from all branches',
          'Present': 'Present',
          'Absent': 'Absent',
          'Consolidated revenue from branches':
              'Consolidated revenue from branches',
          'Today': 'Today',
          'Yesterday': 'Yesterday',
          'This Week': 'This Week',
          'Last Week': 'Last Week',
          'This Month': 'This Month',
          'Last Month': 'Last Month',
          'This Year': 'This Year',
          'Last Year': 'Last Year',
          'Select Date Range': 'Select Date Range',
          'Total Sales': 'Total Sales',
          'Gross Profit': 'Gross Profit',
          'You Sold for Gross profit compared to same day last week':
              'You Sold for Gross profit compared to same day last week',
          'Less': 'Less',
          'More': 'More',
          'Bills': 'Bills',
          'Category': 'Category',
          'Section': 'Section',
          'Item': 'Item',
          'Customer': 'Customer',
          'Customer Group': 'Customer Group',
          'Supplier': 'Supplier',
          'Supplier Group': 'Supplier Group',
          'Brand': 'Brand',
          'TaxCode': 'TaxCode',
          'Sales Trends': 'Sales Trends',
          'No of Bills': 'No of Bills',
          'Total': 'Total',
          'GP Percent': 'GP Percent',
          'Total Credit': 'Total Credit',
          'Tax Amount': 'Tax Amount',
          'Total Receipt': 'Total Receipt',
          'Average Basket Value': 'Average Basket Value',
          'Sales': 'Sales',
          'Sales Return': 'Sales Return',
          'Rounding Amount': 'Rounding Amount',
          'Party Ledger': 'Party Ledger',
          'Item Ledger': 'Item Ledger',
          'Receivable': 'Receivable',
          'Payable': 'Payable',
          'Cash': 'Cash',
          'Bank': 'Bank',
          'Stock Movement': 'Stock Movement',
          'Cash Report': 'Cash Report',
          'Cash and Bank': 'Cash and Bank',
          'Counter Closing': 'Counter Closing',
          'Account payments': 'Account payments',
          'Payments': 'Payments',
          'Account Receipts': 'Account Receipts',
          'Receipts': 'Receipts',
          'Routes': 'Routes',
          'Attendance Details': 'Attendance Details',
          'Leave': 'Leave',
          'Roster': 'Roster',
          'Read Your Business': 'Read Your Business',
          'Sales Order': 'Sales Order',
          'Purchase': 'Purchase',
          'Purchase Order': 'Purchase Order',
          'See More': 'See More',
          'Purchase Return': 'Purchase Return',
          'POS': 'POS',
          'POS Order': 'POS Order',
          'POS Return': 'POS Return',
          'Loss report': 'Loss report',
          'Credit Sale': 'Credit Sale',
          'Manual Journal': 'Manual Journal',
          'Category Stock': 'Category Stock',
          'Day Book': 'Day Book',
          'Cash Flow': 'Cash Flow',
          'Trial Balance': 'Trial Balance',
          'Profit & Loss': 'Profit & Loss',
          'Collapse': 'Collapse',
          'Sales Transaction': 'Sales Transaction',
          'Invoice': 'Invoice',
          'Order': 'Order',
          'Return': 'Return',
          'Purchase Transaction': 'Purchase Transaction',
          'Fund Transfer': 'Fund Transfer',
          'To Party': 'To Party',
          'Journal': 'Journal',
          'Others': 'Others',
          'Receipt': 'Receipt',
          'Payment': 'Payment',
          'Manage Company': 'Manage Company',
          'Training Videos': 'Training Videos',
          'Watch Videos on how to use the App':
              'Watch Videos on how to use the App',
          '24X7 Help': '24X7 Help',
          'Get quick answer to all your business related queries':
              'Get quick answer to all your business related queries',
          'Branch Details': 'Branch Details',
          'Choose a timeline to view analytical data':
              'Choose a timeline to view analytical data',
          'Last 7 day': 'Last 7 day',
          'Last 30 days': 'Last 30 days',
          'Great you have sold for gross profit compared to same day last week':
              'Great you have sold for gross profit compared to same day last week',
          'Sale': 'Sale',
          'Gp': 'Gp',
          'Total Collection': 'Total Collection',
          'Great you collected More compared to last week same day':
              'Great you collected More compared to last week same day',
          'Average Amount per.Payment': 'Average Amount per.Payment',
          'compared to last week same day': 'compared to last week same day',
          'Estimated Expense': 'Estimated Expense',
          'Estimated Netprofit': 'Estimated Netprofit',
          'No Transactions during the selected period':
              'No Transactions during the selected period',
          'Category Trend': 'Category Trend',
          'Number Of Categories': 'Number Of Categories',
          'Section Trends': 'Section Trends',
          'Number Of Section': 'Number Of Section',
          'Item Sales Trends': 'Item Sales Trends',
          'Number Of Items': 'Number Of Items',
          'Number Of Customers': 'Number Of Customers',
          'Number Of Customergroups': 'Number Of Customergroups',
          'Number Of Suppliers': 'Number Of Suppliers',
          'Number Of Supplier Group': 'Number Of Supplier Group',
          'No Details Found': 'No Details Found',
          'Employee Dashboard': 'Employee Dashboard',
          'Sales Dashboard': 'Sales Dashboard',
          'Purchase Dashboard': 'Purchase Dashboard',
          'HRM Dashboard': 'HRM Dashboard',
          'Manager Dashboard': 'Manager Dashboard',
          'Customers': 'Customers',
          'Suppliers': 'Suppliers',
          'Accounts': 'Accounts',
          'Employees': 'Employees',
          'Search': 'Search',
          'Create New Party': 'Create New Party',
          'Name': 'Name',
          'Mobile Number': 'Mobile Number',
          'Email': 'Email',
          'Address': 'Address',
          'Pin Code': 'Pin Code',
          'State': 'State',
          'GST Number': 'GST Number',
          'GST Type': 'GST Type',
          'Price List': 'Price List',
          'Group': 'Group',
          'Save': 'Save',
          'Create New Supplier': 'Create New Supplier',
          'Create New Account': 'Create New Account',
          'Enter Account Name': 'Enter Account Name',
          'Parent Account': 'Parent Account',
          'Asset': 'Asset',
          'Account Code': 'Account Code',
          'Drawer': 'Drawer',
          'Account Type': 'Account Type',
          'Current Asset': 'Current Asset',
          'Create New Employee': 'Create New Employee',
          'To Get': 'To Get',
          'Select date': 'Select date',
          'Search Transactions': 'Search Transactions',
          'Transactions': 'Transactions',
          'Pending Bills': 'Pending Bills',
          'Balance': 'Balance',
          'To Pay': 'To Pay',
          'Manufacturer': 'Manufacturer',
          'Create Item': 'Create Item',
          'Item Name': 'Item Name',
          'MRP': 'MRP',
          'HSN Code': 'HSN Code',
          'BAR Code': 'BAR Code',
          'STATIONARY': 'STATIONARY',
          'Tax': 'Tax',
          'Exempt': 'Exempt',
          'No More Items': 'No More Items',
          'Cash Amount': 'Cash Amount',
          'Bank Amount': 'Bank Amount',
          'Amount': 'Amount',
          'Party Name': 'Party Name',
          'Total Balance Due': 'Total Balance Due',
          'Date': 'Date',
          'Time': 'Time',
          'Document': 'Document',
          'Party Code': 'Party Code',
          'Punch Details': 'Punch Details',
          'Day Details': 'Day Details',
          'Shift begin': 'Shift begin',
          'PM': 'PM',
          'AM': 'AM',
          'Shift end': 'Shift end',
          'First Punch': 'First Punch',
          'Last Punch': 'Last Punch',
          'View Attendance': 'View Attendance',
          'Employee Name': 'Employee Name',
          'Employee Name :': 'Employee Name :',
          'Total Leave': 'Total Leave',
          'Total Leave :': 'Total Leave :',
          'Total Present': 'Total Present',
          'Total Present :': 'Total Present :',
          'Absents List': 'Absents List',
          'Reason': 'Reason',
          'Status': 'Status',
          'Leave Request Not Placed': 'Leave Request Not Placed',
          'All': 'All',
          'Overtime': 'Overtime',
          'Full Day': 'Full Day',
          'Partial attendance': 'Partial attendance',
          'Credit Amount': 'Credit Amount',
          'Bill Date': 'Bill Date',
          'Due Date': 'Due Date',
          'Net Amount': 'Net Amount',
          'Particular': 'Particular',
          'Remarks': 'Remarks',
          'Credit/Debit': 'Credit/Debit',
          'Sales Invoice': 'Sales Invoice',
          'Select Product By': 'Select Product By',
          'Add More': 'Add More',
          'Swipe To Delete': 'Swipe To Delete',
          'UOM': 'UOM',
          'Discount %': 'Discount %',
          'Rate': 'Rate',
          'Freight': 'Freight',
          'Submit': 'Submit',
          'Line Total': 'Line Total',
          'Discount Total': 'Discount Total',
          'Gross Total': 'Gross Total',
          'Credit': 'Credit',
          'Are You Sure': 'Are You Sure',
          'Do You Want to Go Back': 'Do You Want to Go Back',
          'Yes': 'Yes',
          'No': 'No',
          'Party to Party': 'Party to Party',
          'Transaction Date': 'Transaction Date',
          'Dr': 'Dr',
          'Party Balance': 'Party Balance',
          'CANCEL': 'CANCEL',
          'OK': 'OK',
          'Party': 'Party',
          'Mode': 'Mode',
          'Account': 'Account',
          'On Account': 'On Account',
          'Choose Bills': 'Choose Bills',
          'No More Receipt': 'No More Receipt',
          'Card': 'Card',
          'UPI': 'UPI',
          'Sales Document': 'Sales Document',
          'Quantity': 'Quantity',
          'Discount': 'Discount',
          'Discount Amount': 'Discount Amount',
          'Net Total': 'Net Total',
          'Cost': 'Cost',
          'TaxAmount': 'TaxAmount',
          'View Transaction': 'View Transaction',
          'Price': 'Price',
          'On Hand': 'On Hand',
          'Mrp Discount': 'Mrp Discount',
          'inactive': 'inactive',
          'Counted Quantity': 'Counted Quantity',
          'NOTEPAD RULLED & UR METILDA': 'NOTEPAD RULLED & UR METILDA',
          'METILD': 'METILD',
          'Type': 'Type',
          'Update Item': 'Update Item',
          'Store': 'Store',
          'Add New Store': 'Add New Store',
          'Str_Code': 'Str_Code',
          'StrName': 'StrName',
          'OrderReceived': 'OrderReceived',
          'OrderGiven': 'OrderGiven',
          'OnHand': 'OnHand',
          'NetAvailable': 'NetAvailable',
          'AvgPrice': 'AvgPrice',
          'Is Inclusive': 'Is Inclusive',
          'Gp%': 'Gp%',
          'Update Item Count': 'Update Item Count',
          'Enter Count': 'Enter Count',
          'Update': 'Update',
          'Choose a timeline': 'Choose a timeline',
          'compared to same day, last week': 'compared to same day, last week',
          'New Customers': 'New Customers',
          'than last week same day': 'than last week same day',
          'Repeat Customers': 'Repeat Customers',
          'Last week same day': 'Last week same day',
          'Cumulative': 'Cumulative',
          'Purchase Quantity': 'Purchase Quantity',
          'Sales Quantity': 'Sales Quantity',
          'Sales Return Quantity': 'Sales Return Quantity',
          'Purchase Return Quantity': 'Purchase Return Quantity',
          'By store': 'By store',
          'Stock': 'Stock',
          'No Records': 'No Records',
          'Company Manager': 'Company Manager',
          'Please Tap here to re-login': 'Please Tap here to re-login',
          'Notification': 'Notification',
          'Manager Settings': 'Manager Settings',
          'What Changed Since': 'What Changed Since',
          'Menu Items': 'Menu Items',
          'Health of your business': 'Health of your business',
          'Liquidity Score': 'Liquidity Score',
          'Financial DashBoard': 'Financial DashBoard',
          'Debit Credit Analysis': 'Debit Credit Analysis',
          'Cash Convention Cycle': 'Cash Convention Cycle',
          'Profit Ratio': 'Profit Ratio',
          'LogOut': 'LogOut',
          'Expense': 'Expense',
          'Settings': 'Settings',
          'Concise Report': 'Concise Report',
          'Search Category': 'Search Category',
          'Try Again': 'Try Again',
          'Select billed items': 'Select billed items',
          'Add item': 'Add item',
          'GST': 'GST',
          'In null': 'In null',
          'Number Of Sales': 'Number Of Sales',
          'You have sold compared to last month same day':
              'You have sold compared to last month same day',
          'Sales-Return': 'Sales-Return',
          'Total Sales-Return': 'Total Sales-Return',
          'Number Of Sales-Return': 'Number Of Sales-Return',
          'You got returns of compared to last month same day':
              'You got returns of compared to last month same day',
          'Sales-POS': 'Sales-POS',
          'Total Sales-POS': 'Total Sales-POS',
          'Number Of Sales-POS': 'Number Of Sales-POS',
          'Total Purchase': 'Total Purchase',
          'Number Of Purchase': 'Number Of Purchase',
          'Purchase-Order': 'Purchase-Order',
          'Number Of Purchase-Order': 'Number Of Purchase-Order',
          'You have ordered compared to last month same day':
              'You have ordered compared to last month same day',
          'Credit-Sales': 'Credit-Sales',
          'Total Credit-Sales': 'Total Credit-Sales',
          'Number Of Credit-Sales': 'Number Of Credit-Sales',
          'Item Sales': 'Item Sales',
          'Sold at MRP': 'Sold at MRP',
          'Sold With Discount': 'Sold With Discount',
          'Sold at Loss': 'Sold at Loss',
          'Approve Sales': 'Approve Sales',
          'Remark': 'Remark',
          'Reject': 'Reject',
          'Approve': 'Approve',
          'Top Selling Items': 'Top Selling Items',
          'Stock Activity': 'Stock Activity',
          '(In Quantity)': '(In Quantity)',
          'Low Stock': 'Low Stock',
          'Low Stock Details': 'Low Stock Details',
          'Excess Stock': 'Excess Stock',
          'Excess Stock Details': 'Excess Stock Details',
          'Total Variants': 'Total Variants',
          'Total Variants Details': 'Total Variants Details',
          'Total Item Group': 'Total Item Group',
          'Total Item Group Details': 'Total Item Group Details',
          'Cannot find Table': 'Cannot find Table',
          'Sold Today ': 'Sold Today ',
          'Sold Today Details': 'Sold Today Details',
          'Sold This Month': 'Sold This Month',
          'Sold This Month Details': 'Sold This Month Details',
          'Returned Today': 'Returned Today',
          'Returned Today Details': 'Returned Today Details',
          'Returned This Month': 'Returned This Month',
          'Returned This Month Details': 'Returned This Month Details',
          'Users and routes': 'Users and routes',
          'Add New': 'Add New',
          'Select Employee': 'Select Employee',
          'Route Name': 'Route Name',
          'Unit': 'Unit',
          'Cr': 'Cr',
          'Sold At': 'Sold At',
          'With': 'With',
          'At Cost': 'At Cost',
          'Sold To': 'Sold To',
          'with bill number': 'with bill number',
          'Qty': 'Qty',
          'Rs': 'Rs',
          'you collected compared to last week same day':
              'you collected compared to last week same day',
          'Approve Purchase': 'Approve Purchase',
          'Approve Purchase Order': 'Approve Purchase Order',
          'Opening Balance': 'Opening Balance',
          'Goods Receipt Quantity': 'Goods Receipt Quantity',
          'Transaction': 'Transaction',
          'Top purchasing items': 'Top purchasing items',
          'Purchase details': 'Purchase details',
          'Filter By': 'Filter By',
          'Default': 'Default',
          'Ascending': 'Ascending',
          'Descending': 'Descending',
          'Item Purchase': 'Item Purchase',
          'Purchase Trends': 'Purchase Trends',
          'No of Categories': 'No of Categories',
          'Category Details': 'Category Details',
          'Top 10 Category': 'Top 10 Category',
          'has contributed of total sale': 'has contributed of total sale',
          'All Category': 'All Category',
          'No of Section': 'No of Section',
          'Section Details': 'Section Details',
          'Item Purchase Trends': 'Item Purchase Trends',
          'Please wait': 'Please wait',
          'No of Items': 'No of Items',
          'Date Range': 'Date Range',
          'Menu': 'Menu',
          'Designation Master': 'Designation Master',
          'Attendance Insert': 'Attendance Insert',
          'Pay Roll List': 'Pay Roll List',
          'Shift Master': 'Shift Master',
          'Designation Title': 'Designation Title',
          'Select Options': 'Select Options',
          'Sales Staff': 'Sales Staff',
          'Finance Manager': 'Finance Manager',
          'Manager': 'Manager',
          'Create Designation': 'Create Designation',
          'Promotion Title': 'Promotion Title',
          'Select All': 'Select All',
          'Late By': 'Late By',
          'Minute': 'Minute',
          'Sent Request': 'Sent Request',
          'Half Day': 'Half Day',
          'Late Day': 'Late Day',
          'Part Time Full': 'Part Time Full',
          'Nos': 'Nos',
          'value': 'value',
          'Pay Slip': 'Pay Slip',
          'TAKE HOME': 'TAKE HOME',
          'DEDUCTIONS': 'DEDUCTIONS',
          'Total Gross Pay': 'Total Gross Pay',
          'Earnings (A)': 'Earnings (A)',
          'Basic Salary (Gross Salary)': 'Basic Salary (Gross Salary)',
          'Total Earnings': 'Total Earnings',
          'Deductions (B)': 'Deductions (B)',
          'Total Deductions': 'Total Deductions',
          'TAKE HOME (A) - (B)': 'TAKE HOME (A) - (B)',
          'Actual Salary': 'Actual Salary',
          'Basic Salary': 'Basic Salary',
          'Create Shift': 'Create Shift',
          'Shift Name': 'Shift Name',
          'Shift Code': 'Shift Code',
          'Shift Value': 'Shift Value',
          'Pick Color': 'Pick Color',
          'Pick a color': 'Pick a color',
          'RGB': 'RGB',
          'Hex': 'Hex',
          'Select': 'Select',
          'Requests': 'Requests',
          'You dont have any pending request':
              'You dont have any pending request',
          'Roaster': 'Roaster',
          'Create Pay Roll': 'Create Pay Roll',
          'Departments': 'Departments',
          'Emp Name': 'Emp Name',
          'NO SALES PERSON': 'NO SALES PERSON',
          'Edit': 'Edit',
          'Updated': 'Updated',
          'Pay Roll': 'Pay Roll',
          'Number Of Days': 'Number Of Days',
          'Choose Dashboard': 'Choose Dashboard',
          'Employee Balance': 'Employee Balance',
          'Pending Tasks': 'Pending Tasks',
          'Punch': 'Punch',
          'Select Location': 'Select Location',
          'Punch In': 'Punch In',
          'Punch Out': 'Punch Out',
          'Leave Request': 'Leave Request',
          'Select a Date or Date-Range': 'Select a Date or Date-Range',
          'Start date - End Date': 'Start date - End Date',
          'Select Leave Type': 'Select Leave Type',
          'No.Of Days': 'No.Of Days',
          'Add Leave Type': 'Add Leave Type',
          'AlertDialog Title': 'AlertDialog Title',
          'Enter Leave Type': 'Enter Leave Type',
          'Claim And Allowance': 'Claim And Allowance',
          'Advance': 'Advance',
          'Select Expense Type': 'Select Expense Type',
          'Select Your Document From': 'Select Your Document From',
          'Camera': 'Camera',
          'Gallery': 'Gallery',
          'Attendance Log': 'Attendance Log',
          'Attendance List': 'Attendance List',
          'Reimburse': 'Reimburse',
          'Reimbursement': 'Reimbursement',
          'Add Activity': 'Add Activity',
          'What': 'What',
          'When': 'When',
          'From': 'From',
          'To': 'To',
          'Where': 'Where',
          'Total Working Days': 'Total Working Days',
          'Promotion': 'Promotion',
          'Request For Promotion': 'Request For Promotion',
          'From Designation': 'From Designation',
          'To Designation': 'To Designation',
          'Enter Remarks': 'Enter Remarks',
          'My Attendance': 'My Attendance',
          'My Routes': 'My Routes',
          'Employee Master': 'Employee Master',
          'Employee Details': 'Employee Details',
          'E-Mail': 'E-Mail',
          'Personal Details': 'Personal Details',
          'Account Details': 'Account Details',
          'Bank Name': 'Bank Name',
          'Branch Name': 'Branch Name',
          'Account Number': 'Account Number',
          'IFSC Code': 'IFSC Code',
          'Account Holder Name': 'Account Holder Name',
          'GL Account': 'GL Account',
          'Commission Account': 'Commission Account',
          'Leave Account': 'Leave Account',
          'Salary Bricks': 'Salary Bricks',
          'Statutory Charges': 'Statutory Charges',
          'Attendance': 'Attendance'
        },
        'ar_SA': {
          'Company Name': 'اسم الشركة',
          'User Name': 'اسم االمستخدم',
          'Password': 'كلمة المرور',
          'Login': 'تسجيل الدخول',
          'Consolidated Attendance from all branches':
              'حضور موحد من جميع الفروع',
          'Present': 'الحضور',
          'Absent': 'غائب',
          'Consolidated revenue from branches': 'الإيرادات المجمعة من الفروع',
          'Today': 'اليوم',
          'Yesterday': 'في الامس',
          'This Week': 'هذا الاسبوع',
          'Last Week': 'الأسبوع الماضي',
          'This Month': 'هذا الشهر',
          'Last Month': 'الشهر الماضي',
          'This Year': 'هذه السنة',
          'Last Year': 'العام الماضي',
          'Select Date Range': 'حدد النطاق الزمني',
          'Total Sales': 'إجمالي المبيعات',
          'Gross Profit': 'اجمالي الربح',
          'You Sold for Gross profit compared to same day last week':
              'لقد بعت لإجمالي الربح مقارنة بنفس اليوم الأسبوع الماضي',
          'Less': 'أقل',
          'More': 'أكثر',
          'Bills': 'الفواتير',
          'Category': 'فئة',
          'Section': 'الجزء',
          'Item': 'صنف',
          'Customer': 'عميل',
          'Customer Group': 'مجموعة العملاء',
          'Supplier': 'المورد',
          'Supplier Group': 'مجموعة الموردين',
          'Brand': 'ماركة',
          'TaxCode': 'قانون الضرائب',
          'Sales Trends': 'اتجاهات المبيعات',
          'No of Bills': 'عدد الفواتير',
          'Total': 'المجموع',
          'GP Percent': 'إجمالي الربح',
          'Total Credit': 'إجمالي الائتمان',
          'Tax Amount': 'قيمة الضريبة',
          'Total Receipt': 'إجمالي الإيصال',
          'Average Basket Value': 'متوسط ​​قيمة السلة',
          'Sales': 'مبيعات',
          'Sales Return': 'مرتجع المبيعات',
          'Rounding Amount': 'مبلغ التقريب',
          'Party Ledger': 'دفتر الآستاذ للأطراف',
          'Item Ledger': 'دفتر الأستاذ للصنف',
          'Receivable': 'مستحق',
          'Payable': 'مستحق الدفع',
          'Cash': 'نقدي',
          'Bank': 'بنك',
          'Stock Movement': 'حركة المخزون',
          'Cash Report': 'تقرير النقدية',
          'Cash and Bank': 'النقد والبنك',
          'Counter Closing': 'إغلاق طاولة البيع',
          'Account payments': 'مدفوعات الحساب',
          'Payments': 'المدفوعات',
          'Account Receipts': 'إيصالات الحساب',
          'Receipts': 'الإيصالات',
          'Routes': 'طرق',
          'Attendance Details': 'تفاصيل الحضور',
          'Leave': 'إجازة',
          'Roster': 'قائمة',
          'Read Your Business': 'اقرأ عملك',
          'Sales Order': 'طلب المبيعات',
          'Purchase': 'شراء',
          'Purchase Order': 'أمر شراء',
          'See More': 'شاهد المزيد',
          'Purchase Return': 'مرتجع شراء',
          'POS': 'نقاط البيع',
          'POS Order': 'طلب نقاط البيع',
          'POS Return': 'مرتجع نقاط البيع',
          'Loss report': 'تقرير الخسارة',
          'Credit Sale': 'بيع للإئتمان',
          'Manual Journal': 'دفتر يدوي',
          'Category Stock': 'فئة المخزون',
          'Day Book': 'دفتر اليوم',
          'Cash Flow': 'تدفق النقد',
          'Trial Balance': 'ميزان المراجعة',
          'Profit & Loss': 'أرباح وخسائر',
          'Collapse': 'انهيار',
          'Sales Transaction': 'معاملات البيع',
          'Invoice': 'فاتورة',
          'Order': 'طلب',
          'Return': 'مرتجع',
          'Purchase Transaction': 'معاملة الشراء',
          'Fund Transfer': 'تحويل الأموال',
          'To Party': 'إلى أطراف',
          'Journal': 'دفتر',
          'Others': 'أخرى',
          'Receipt': 'إيصال',
          'Payment': 'دفع',
          'Manage Company': 'إدارة الشركة',
          'Training Videos': 'فيديوهات تدريبية',
          'Watch Videos on how to use the App':
              'شاهد مقاطع فيديو حول كيفية استخدام التطبيق',
          '24X7 Help': '24X7 مساعدة',
          'Get quick answer to all your business related queries':
              'احصل على إجابة سريعة لجميع الاستفسارات المتعلقة بأعمالك',
          'Branch Details': 'تفاصيل الفرع',
          'Choose a timeline to view analytical data':
              'اختر جدولاً زمنياً لعرض البيانات التحليلية',
          'Last 7 day': 'آخر 7 أيام',
          'Last 30 days': 'آخر 30 يومًا',
          'Great you have sold for gross profit compared to same day last week':
              'لقد قمت ببيعها لتحقيق ربح إجمالي مقارنة بنفس اليوم الأسبوع الماضي',
          'Sale': 'تخفيض السعر',
          'Gp': 'إجمالي الربح',
          'Total Collection': 'المجموع الكلي',
          'Great you collected More compared to last week same day':
              'رائع أنك جمعت أكثر مقارنة بالأسبوع الماضي في نفس اليوم',
          'Average Amount per.Payment': 'متوسط ​​المبلغ لكل دفعة',
          'compared to last week same day':
              'مقارنة بالأسبوع الماضي في نفس اليوم',
          'Estimated Expense': 'المصاريف المقدرة',
          'Estimated Netprofit': 'صافي الربح المقدر',
          'No Transactions during the selected period':
              'لا توجد معاملات خلال الفترة المحددة',
          'Category Trend': 'اتجاهات الفئات',
          'Number Of Categories': 'عدد الفئات',
          'Section Trends': 'اتجاهات القسم',
          'Number Of Section': 'رقم القسم',
          'Item Sales Trends': 'اتجاهات مبيعات الصنف',
          'Number Of Items': 'عدد الأصناف',
          'Number Of Customers': 'عدد الزبائن',
          'Number Of Customergroups': 'عدد المجموعات المخصصة',
          'Number Of Suppliers': 'عدد الموردين',
          'Number Of Supplier Group': 'عدد من مجموعة الموردين',
          'No Details Found': 'لم يتم العثور على تفاصيل',
          'Employee Dashboard': 'لوحة المعلومات الموظف',
          'Sales Dashboard': 'لوحة المبيعات',
          'Purchase Dashboard': 'شراء لوحة المعلومات',
          'HRM Dashboard': 'لوحة معلومات إدارة الموارد البشرية',
          'Manager Dashboard': 'مسؤول لوحة المعلومات',
          'Customers': 'عملاء',
          'Suppliers': 'الموردين',
          'Accounts': 'حسابات',
          'Employees': 'الموظفين',
          'Search': 'بحث',
          'Create New Party': 'إنشاء طرف جديدة',
          'Name': 'اسم',
          'Mobile Number': 'رقم الهاتف المحمول',
          'Email': 'البريد الإلكتروني',
          'Address': 'عنوان البريد',
          'Pin Code': 'الرقم السري',
          'State': 'حالة',
          'GST Number': 'رقم ضريبة السلع والخدمات',
          'GST Type': 'نوع ضريبة السلع والخدمات',
          'Price List': 'قائمة الاسعار',
          'Group': 'مجموعة',
          'Save': 'حفظ',
          'Create New Supplier': 'إنشاء مورد جديد',
          'Create New Account': 'انشاء حساب جديد',
          'Enter Account Name': 'أدخل اسم الحساب',
          'Parent Account': 'الحساب الأب',
          'Asset': 'أصل',
          'Account Code': 'رمز الحساب',
          'Drawer': 'ساحسب',
          'Account Type': 'نوع الحساب',
          'Current Asset': 'الأصول المتداولة',
          'Create New Employee': 'إنشاء موظف جديد',
          'To Get': 'للحصول على',
          'Select date': 'حدد تاريخ',
          'Search Transactions': 'معاملات البحث',
          'Transactions': 'المعاملات',
          'Pending Bills': 'الفواتير المعلقة',
          'Balance': 'الرصيد',
          'To Pay': 'للدفع',
          'Manufacturer': 'الصانع',
          'Create Item': 'إنشاء صنف',
          'Item Name': 'اسم الصنف',
          'MRP': 'سعر التجزئة الأقصى',
          'HSN Code': '',
          'BAR Code': 'الرمز الشريطي',
          'STATIONARY': 'ثابت',
          'Tax': 'ضريبة',
          'Exempt': 'معفى',
          'No More Items': 'لا مزيد من الأصناف',
          'Cash Amount': 'مبلغ نقدي',
          'Bank Amount': 'مبلغ البنك',
          'Amount': 'مقدار',
          'Party Name': 'اسم الطرف',
          'Total Balance Due': 'إجمالي الرصيد المستحق',
          'Date': 'تاريخ',
          'Time': 'زمن',
          'Document': 'وثيقة',
          'Party Code': 'رمز الطرف',
          'Punch Details': 'تفاصيل البصمة',
          'Day Details': 'تفاصيل اليوم',
          'Shift begin': 'شروع فترة العمل',
          'PM': 'مساءً',
          'AM': 'صباحا',
          'Shift end': 'نهاية فترة العمل',
          'First Punch': 'البصمة الأولى',
          'Last Punch': 'آخر بصمة',
          'View Attendance': 'مشاهدة ملف الحضور',
          'Employee Name': 'اسم الموظف',
          'Employee Name :': 'اسم الموظف',
          'Total Leave': 'إجمالي الإجازة',
          'Total Leave :': ': إجمالي الإجازة',
          'Total Present': 'إجمالي الحضور',
          'Total Present :': ': إجمالي الحضور',
          'Absents List': 'قائمة الغائبين',
          'Reason': 'سبب',
          'Status': 'حالة',
          'Leave Request Not Placed': 'لم يتم تقديم طلب الإجازة',
          'All': 'الجميع',
          'Overtime': 'متأخر , بعد فوات الوقت',
          'Full Day': 'يوم كامل',
          'Partial attendance': 'الحضور الجزئي',
          'Credit Amount': 'مبلغ الائتمان',
          'Bill Date': 'تاريخ الفاتورة',
          'Due Date': 'تاريخ الاستحقاق',
          'Net Amount': 'صافي المبلغ',
          'Particular': 'خاص',
          'Remarks': 'ملاحظات',
          'Credit/Debit': 'الائتمان / الخصم',
          'Sales Invoice': 'فاتورة المبيعات',
          'Select Product By': 'حدد المنتج حسب',
          'Add More': 'أضف المزيد',
          'Swipe To Delete': 'مسح للحذف',
          'UOM': 'وحدة القياس',
          'Discount %': 'تخفيض ٪',
          'Rate': 'معدل',
          'Freight': 'شحن',
          'Submit': 'تقديم',
          'Line Total': 'مجموعه الأصناف',
          'Discount Total': 'إجمالي الخصم',
          'Gross Total': 'المجموع الكلي',
          'Credit': 'ائتمان',
          'Are You Sure': 'هل أنت متأكد',
          'Do You Want to Go Back': 'هل تريد العودة',
          'Yes': 'نعم',
          'No': 'رقم',
          'Party to Party': 'من طرف إلى طرف',
          'Transaction Date': 'تاريخ المعاملة',
          'Dr': '',
          'Party Balance': 'رصيد الطرف',
          'CANCEL': 'إلغاء',
          'OK': 'نعم',
          'Party': 'طرف',
          'Mode': 'الوضع',
          'Account': 'الحساب',
          'On Account': 'على حساب',
          'Choose Bills': 'اختر الفواتير',
          'No More Receipt': 'لا مزيد من الإيصال',
          'Card': 'بطاقة',
          'UPI': '',
          'Sales Document': 'مستند المبيعات',
          'Quantity': 'كمية',
          'Discount': 'تخفيض',
          'Discount Amount': 'مقدار الخصم',
          'Net Total': 'صافي الإجمالي',
          'Cost': 'تكلفة',
          'TaxAmount': 'قيمة الضريبة',
          'View Transaction': 'عرض المعاملة',
          'Price': 'سعر',
          'On Hand': 'علي اليد',
          'Mrp Discount': 'خصم على سعر التجزئة الأقصى',
          'inactive': 'غير نشط',
          'Counted Quantity': 'الكمية المحسوبة',
          'NOTEPAD RULLED & UR METILDA': '',
          'METILD': '',
          'Type': 'كتابة',
          'Update Item': 'تحديث الصنف',
          'Store': 'مستودع',
          'Add New Store': 'إضافة مستودع جديد',
          'Str_Code': 'Str_Code',
          'StrName': 'StrName',
          'OrderReceived': 'تم استلام الطلب',
          'OrderGiven': 'تم إرسال الطلب',
          'OnHand': 'علي اليد',
          'NetAvailable': 'صافي الوجود',
          'AvgPrice': 'متوسط ​​السعر',
          'Is Inclusive': 'شامل',
          'Gp%': 'إجمالي الربح',
          'Update Item Count': 'تحديث عدد الأصناف',
          'Enter Count': 'أدخل عدد',
          'Update': 'تحديث',
          'Choose a timeline': 'اختر مخططًا زمنيًا',
          'compared to same day, last week':
              'مقارنة بنفس اليوم ، الأسبوع الماضي',
          'New Customers': 'زبائن الجدد',
          'than last week same day': 'من الأسبوع الماضي في نفس اليوم',
          'Repeat Customers': 'العملاء المتكررين',
          'Last week same day': 'الأسبوع الماضي نفس اليوم',
          'Cumulative': 'تراكمي',
          'Purchase Quantity': 'كمية الشراء',
          'Sales Quantity': 'كمية المبيعات',
          'Sales Return Quantity': 'كمية مرتجعات المبيعات',
          'Purchase Return Quantity': 'كمية مرتجع الشراء',
          'By store': 'حسب المستودع',
          'Stock': 'مخزون',
          'No Records': 'لا تسجيلات',
          'Company Manager': 'مدير الشركة',
          'Please Tap here to re-login': 'الرجاء الضغط هنا لإعادة تسجيل الدخول',
          'Notification': 'تنبيه',
          'Manager Settings': 'إعدادات المدير',
          'What Changed Since': 'ما الذي تغير منذ ذلك الحين',
          'Menu Items': 'أصناف القائمة',
          'Health of your business': 'صحة عملك',
          'Liquidity Score': 'نقاط السيولة',
          'Financial DashBoard': 'لوحة المعلومات المالية',
          'Debit Credit Analysis': 'تحليل الدائن والمدين',
          'Cash Convention Cycle': 'دورة اتفاقية النقدية',
          'Profit Ratio': 'نسبة الربح',
          'LogOut': 'تسجيل خروج',
          'Expense': 'مصروف',
          'Settings': 'إعدادات',
          'Concise Report': 'تقرير موجز',
          'Search Category': 'فئة البحث',
          'Try Again': 'حاول ثانية',
          'Select billed items': 'حدد الأصناف التي تمت فوترتها',
          'Add item': 'اضافة الصنف',
          'GST': 'ضريبة السلع والخدمات',
          'In null': 'فارغ',
          'Number Of Sales': 'عدد المبيعات',
          'You have sold compared to last month same day':
              'لقد قمت بالبيع مقارنة بالشهر الماضي في نفس اليوم',
          'Sales-Return': 'مرتجع المبيعات',
          'Total Sales-Return': 'إجمالي المبيعات - مرتجع',
          'Number Of Sales-Return': 'عدد المبيعات والمرتجعات',
          'You got returns of compared to last month same day':
              'لقد حصلت على مرتجعات مقارنة بالشهر الماضي في نفس اليوم',
          'Sales-POS': 'المبيعات - نقاط البيع',
          'Total Sales-POS': 'إجمالي المبيعات - نقاط البيع',
          'Number Of Sales-POS': 'عدد المبيعات - نقاط البيع',
          'Total Purchase': 'إجمالي الشراء',
          'Number Of Purchase': 'عدد المشتريات',
          'Purchase-Order': 'أمر شراء',
          'Number Of Purchase-Order': 'عدد طلبات الشراء',
          'You have ordered compared to last month same day':
              'لقد طلبت مقارنة الشهر الماضي في نفس اليوم',
          'Credit-Sales': 'مبيعات الائتمان',
          'Total Credit-Sales': 'إجمالي مبيعات الائتمان',
          'Number Of Credit-Sales': 'عدد مبيعات الائتمان',
          'Item Sales': 'مبيعات الأصناف',
          'Sold at MRP': 'تم بيعه لسعر التجزئة الأقصى',
          'Sold With Discount': 'تباع مع الخصم',
          'Sold at Loss': 'تباع في الخسارة',
          'Approve Sales': 'الموافقة على المبيعات',
          'Remark': 'ملاحظة',
          'Reject': 'رفض',
          'Approve': 'موافقة',
          'Top Selling Items': 'الأصناف الأكثر مبيعًا',
          'Stock Activity': 'نشاط المخزون',
          '(In Quantity)': '(في الكمية)',
          'Low Stock': 'المخزون المنخفضة',
          'Low Stock Details': 'تفاصيل المخزون المنخفض',
          'Excess Stock': 'المخزون الفائض',
          'Excess Stock Details': 'تفاصيل المخزون الفائض',
          'Total Variants': 'إجمالي المتغيرات',
          'Total Variants Details': 'تفاصيل المتغيرات الإجمالية',
          'Total Item Group': 'إجمالي مجموعة الأصناف',
          'Total Item Group Details': 'تفاصيل مجموعة الأصناف الإجمالية',
          'Cannot find Table': 'لا يمكن العثور على الجدول',
          'Sold Today ': 'تم بيعه اليوم',
          'Sold Today Details': 'تفاصيل ما تم بيعه اليوم',
          'Sold This Month': 'تم بيعه هذا الشهر',
          'Sold This Month Details': 'تفاصيل مبيعات اليوم',
          'Returned Today': 'مرتجعات اليوم',
          'Returned Today Details': 'تفاصيل مرتجعات اليوم',
          'Returned This Month': 'مرتجعات هذا الشهر',
          'Returned This Month Details': 'تفاصيل مرتجعات هذا الشهر',
          'Users and routes': 'المستخدمون والطرق',
          'Add New': 'إضافة الجديد',
          'Select Employee': 'حدد الموظف',
          'Route Name': 'اسم الطريق',
          'Unit': 'وحدة',
          'Cr': 'دائن',
          'Sold At': 'تم البيع لــ',
          'With': 'مع',
          'At Cost': 'بتكلفة',
          'Sold To': 'تم البيع إلى',
          'with bill number': 'مع رقم الفاتورة',
          'Qty': 'الكمية',
          'Rs': 'روبية',
          'you collected compared to last week same day':
              'قمت بجمعها مقارنة بالأسبوع الماضي في نفس اليوم',
          'Approve Purchase': 'الموافقة على الشراء',
          'Approve Purchase Order': 'الموافقة على أمر الشراء',
          'Opening Balance': 'الرصيد الافتتاحي',
          'Goods Receipt Quantity': 'كمية في استلام البضائع',
          'Transaction': 'معاملة',
          'Top purchasing items': 'الأصناف الأكثر شراءً',
          'Purchase details': 'تفاصيل شراء',
          'Filter By': 'تصفية بواسطة',
          'Default': 'تقصير',
          'Ascending': 'تصاعدي',
          'Descending': 'تنازلي',
          'Item Purchase': 'شراء الأصناف',
          'Purchase Trends': 'اتجاهات الشراء',
          'No of Categories': 'عدد الفئات',
          'Category Details': 'تفاصيل الفئة',
          'Top 10 Category': 'أفضل 10 فئات',
          'has contributed of total sale': 'ساهم في إجمالي البيع',
          'All Category': 'كل الفئات',
          'No of Section': 'رقم القسم',
          'Section Details': 'تفاصيل القسم',
          'Item Purchase Trends': 'اتجاهات شراء الصنف',
          'Please wait': 'يرجى الإنتظار',
          'No of Items': 'عدد الأصناف',
          'Date Range': 'نطاق التاريخ',
          'Menu': 'قائمة الطعام',
          'Designation Master': 'إعدادات المناصب',
          'Attendance Insert': 'إدراج الحضور',
          'Pay Roll List': 'قائمة الأجور',
          'Shift Master': 'إعدادات فترة الدوام',
          'Designation Title': 'عنوان المنصب',
          'Select Options': 'تحديد  الخيارات',
          'Sales Staff': 'موظفي المبيعات',
          'Finance Manager': 'المدير المالي',
          'Manager': 'مدير',
          'Create Designation': 'إنشاء المنصب',
          'Promotion Title': 'عنوان الترويج',
          'Select All': 'اختر الكل',
          'Late By': 'متأخر لمدة',
          'Minute': 'دقيقة',
          'Sent Request': 'إرسال الطلب',
          'Half Day': 'نصف يوم',
          'Late Day': 'يوم التأخير',
          'Part Time Full': 'دوام جزئي كامل',
          'Nos': '',
          'value': 'القيمة',
          'Pay Slip': 'قسيمة الدفع',
          'TAKE HOME': 'صافي المرتب',
          'DEDUCTIONS': 'الاقتطاعات',
          'Total Gross Pay': 'إجمالي المرتب',
          'Earnings (A)': 'أرباح (أ)',
          'Basic Salary (Gross Salary)': 'الراتب الأساسي (الراتب الإجمالي)',
          'Total Earnings': 'الأرباح الكلية',
          'Deductions (B)': 'الاقتطاعات (ب)',
          'Total Deductions': 'إجمالي الاقتطاعات',
          'TAKE HOME (A) - (B)': 'صافي المرتب  (أ) - (ب)',
          'Actual Salary': 'الراتب الفعلي',
          'Basic Salary': 'راتب اساسي',
          'Create Shift': 'إنشاء فترة الزمان',
          'Shift Name': 'اسم فترة الدوام',
          'Shift Code': 'رمز فترة الدوام',
          'Shift Value': 'قيمة فترة الدوام',
          'Pick Color': 'اختر اللون',
          'Pick a color': 'اختر لونا',
          'RGB': '',
          'Hex': 'عرافة',
          'Select': 'حدد',
          'Requests': 'الطلبات',
          'You dont have any pending request': 'ليس لديك أي طلب معلق',
          'Roaster': 'محمصة',
          'Create Pay Roll': 'إنشاء قائمة دفع',
          'Departments': 'الإدارات',
          'Emp Name': 'اسم العميل',
          'NO SALES PERSON': 'لا يوجد مندوب مبيعات',
          'Edit': 'تحرير',
          'Updated': 'تحديث',
          'Pay Roll': 'كشف رواتب',
          'Number Of Days': 'عدد الأيام',
          'Choose Dashboard': 'اختر لوحة المعلومات',
          'Employee Balance': 'رصيد الموظف',
          'Pending Tasks': 'المهام العالقة',
          'Punch': 'بصمة',
          'Select Location': 'اختر المكان',
          'Punch In': 'بصمة الدخول',
          'Punch Out': 'بصمة الخروج',
          'Leave Request': 'طلب إجازة',
          'Select a Date or Date-Range': 'حدد تاريخًا أو نطاقًا زمنيًا',
          'Start date - End Date': 'تاريخ البدء تاريخ الانتهاء',
          'Select Leave Type': 'حدد نوع الإجازة',
          'No.Of Days': 'عدد الأيام',
          'Add Leave Type': 'إضافة نوع الإجازة',
          'AlertDialog Title': 'عنوان حوار التنبيه',
          'Enter Leave Type': 'أدخل نوع الإجازة',
          'Claim And Allowance': 'المطالبة والمخصصات',
          'Advance': 'سلفة',
          'Select Expense Type': 'حدد نوع المصاريف',
          'Select Your Document From': 'حدد المستند الخاص بك من',
          'Camera': 'آلة تصوير',
          'Gallery': 'صالة عرض',
          'Attendance Log': 'سجل الحضور',
          'Attendance List': 'قائمة الحضور',
          'Attendance': 'الحضور',
          'Reimburse': 'سداد التعويض',
          'Reimbursement': 'السداد',
          'Add Activity': 'أضف نشاط',
          'What': 'ماذا',
          'When': 'متي',
          'From': 'من',
          'To': 'إلى',
          'Where': 'أين',
          'Total Working Days': 'إجمالي أيام العمل',
          'Promotion': 'ترقية وظيفية',
          'Request For Promotion': 'طلب ترقية',
          'From Designation': 'من منصب',
          'To Designation': 'إلى منصب',
          'Enter Remarks': 'أدخل الملاحظات',
          'My Attendance': 'حضوري',
          'My Routes': 'مساراتي',
          'Employee Master': 'إعدادات الموظف',
          'Employee Details': 'تفاصيل الموظف',
          'E-Mail': 'البريد الإلكتروني',
          'Personal Details': 'تفاصيل شخصية',
          'Account Details': 'تفاصيل الحساب',
          'Bank Name': 'اسم البنك',
          'Branch Name': 'اسم الفرع',
          'Account Number': 'رقم حساب',
          'IFSC Code': '',
          'Account Holder Name': 'اسم صاحب الحساب',
          'GL Account': 'حساب غوغل',
          'Commission Account': 'حساب العمولة',
          'Leave Account': 'مغادرة الحساب',
          'Salary Bricks': 'طوب الراتب',
          'Statutory Charges': 'الرسوم النظامية ع',
        }
      };
}
